service: prettier-html

provider:
  name: aws
  runtime: nodejs6.10

functions:
  prettier:
    handler: dist/handler.prettify
    events:
      - http:
          path: prettier/v1
          method: post
          cors: true
